###########
# Player  #
###########
vo=gpu-next
gpu-api=vulkan
gpu-context=macvk
hwdec=videotoolbox              # Native Apple Silicon hardware decoding
msg-color=yes
msg-module=yes
hr-seek-framedrop=no
save-position-on-quit
no-resume-playback
border=no                       # Required for ModernX OSC
autofit=85%x85%
cursor-autohide=100

###############
# Screenshots #
###############
screenshot-template="%x/Screens/Screenshot-%F-T%wH.%wM.%wS.%wT-F%{estimated-frame-number}"
screenshot-format=png
screenshot-png-compression=4
screenshot-tag-colorspace=yes
screenshot-high-bit-depth=yes

###########
# OSC/OSD #
###########
osc=no                          # Required for ModernX OSC
osd-bar=yes
osd-font='Inter Tight Medium'
osd-font-size=30
osd-color='#CCFFFFFF'
osd-border-color='#DD322640'
osd-bar-align-y=-1
osd-border-size=2
osd-bar-h=1
osd-bar-w=60

#############
# Subtitles #
#############
sub-auto=fuzzy
sub-ass-vsfilter-blur-compat=yes
sub-ass-scale-with-window=no
embeddedfonts=yes
demuxer-mkv-subtitle-preroll=yes
sub-file-paths-append=ass:srt:sub:subs:subtitles

# Subtitle Styling
sub-font=Open Sans SemiBold
sub-font-size=46
sub-blur=0.3
sub-color=0.9/0.9/0.9/1.0
sub-border-color=0.0/0.0/0.0/0.8
sub-border-size=3.2
sub-margin-x=100
sub-margin-y=50
sub-shadow-offset=0

#########
# Audio #
#########
ao=coreaudio
audio-stream-silence
audio-file-auto=fuzzy
audio-pitch-correction=yes
alang=eng,en,enUS,en-US,jpn,jp,de,ger
slang=eng,en,und,de,ger,jp,jap

###########################
# Video Quality & Scaling #
###########################
profile=high-quality
fbo-format=rgba16hf             # 16-bit precision optimized for Apple GPU
dither-depth=auto

# Scaling
scale=ewa_lanczos
dscale=catmull_rom
cscale=lanczos
sigmoid-upscaling=yes

# Debanding
deband=yes
deband-iterations=4
deband-threshold=35
deband-range=16
deband-grain=48

#######################################
# HDR & Display (Optimized for XDR)   #
#######################################
target-colorspace-hint=yes      # Triggers macOS Native HDR/EDR
hdr-compute-peak=yes
tone-mapping=bt.2446a

#######################################
# Interpolation (Optimized for 120Hz) #
#######################################
video-sync=display-resample
interpolation=yes
tscale=sphinx
tscale-blur=0.699155
tscale-radius=1.05
tscale-clamp=0.0

############
# Playback #
############
deinterlace=no

[protocol.http]
hls-bitrate=max
cache=yes
no-cache-pause

[protocol.https]
profile=protocol.http

[protocol.ytdl]
profile=protocol.http
