# Path to my oh-my-zsh config
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM=~/.dotfiles/zsh/oh-my-zsh-custom
export ZSH_THEME="spaceship"
zstyle ':omz:plugins:nvm' lazy yes
plugins=(git extract macos safe-paste vscode)

source $ZSH/oh-my-zsh.sh

# PATH
export PATH="/usr/local:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/Developer:$PATH"
export PATH="$HOME/Developer/jslpc/scripts:$PATH"
# Python + pip
export PATH="/opt/homebrew/opt/python@3.11/libexec/bin:$PATH"
export PATH="$HOME/Library/Python/3.11/bin:$PATH"
export PATH="$PATH:$HOME/.local/bin"

# Other apps
export BEETSDIR=~/.dotfiles/beets
export EDITOR=code
export MPV_HOME=~/.config/mpv

# Prevent rm -f from asking for confirmation on things like `rm -f *.bak`
setopt rm_star_silent

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

typeset -U PATH

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

