# Path to your oh-my-zsh config
export ZSH="/Users/jake/.oh-my-zsh"
export ZSH_CUSTOM=~/.dotfiles/zsh/oh-my-zsh-custom
export ZSH_THEME="spaceship"
# CASE_SENSITIVE="true"
plugins=(git extract macos safe-paste nvm vscode)
zstyle ':omz:plugins:nvm' lazy yes

source $ZSH/oh-my-zsh.sh

# PATH
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="/usr/local/sbin:$PATH"
export PATH="/Users/Jake/.local/bin:$PATH"
export PATH="/Users/Jake/CLI:$PATH"
export PATH="/Users/Jake/CLI/beets:$PATH"
export PATH="/opt/homebrew/opt/python@3.11/libexec/bin:$PATH"

# Other variables
export NVM_DIR=~/.nvm
export BEETSDIR=~/.dotfiles/beets
export EDITOR=code

# Prevent rm -f from asking for confirmation on things like `rm -f *.bak`
setopt rm_star_silent

# Evaluate
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
eval "$(direnv hook zsh)"

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
